services:
  backend:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
    image: micro
    container_name: micro_serv
    ports:
      - 8000:8000

  db:
    image: postgres:15
    container_name: database
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/app/testdata/

volumes:
  pgdata: