name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}

    steps:

    - name: checkout code
      uses: actions/checkout@v3

    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: install dependencies
      run: | 
        pip install -r requirements.txt

    - name: run containers
      run: docker compose up -d --build

    - name: wait for python to be rdy
      run: |
        for i in {1..10}; do
        if curl -f http://localhost:8000; then
          echo "backend is ready";
          exit 0;
        fi
        echo "waiting for backend";
        sleep 3;
          done
          echo "backend failed to start";
          docker logs micro
          exit 1

    - name: run tests
      run: pytest tests.py


      
